#include<iostream.h>
#include<conio.h>
void/*argument*/ main() // main function
{    // opening parenthesis of main body
  clrscr();//system("cls"); can also be used for some specific compilers
  cout<<"Welocme to C++ Programing";// cout stands for consol output
  cout<<"\nPress any ket to exit......";//"\n" works same as enter in word
  getch();// used for holding the output on screen
} // closing paranthesis of main body